#!/bin/bash

file=$1

mod () {
	local t=$1
	local num=$2
	bestT=-1
	# Find the time closest to t in file
	while read line; do
		if [[ $line =~ ^[0-9].*$ ]]; then
			lineT=`echo $line | awk '{print $1}'`
			if [ $lineT -le $t ] || [ $bestT -eq -1 ]; then bestT=$lineT
			else break
			fi
		fi
	done <<< `cat $file`
	# Modify that line
	echo "fixing t=$bestT: $num"
	sed -i "s/^$bestT \(.*\)/$bestT \1 $num/" $file
}

lastT=0
num=0
sleepDat="`grep "# Submitted sleep" long2 | sed 's/# Submitted sleep \([0-9]*\) at t=\([0-9]*\)/\2 \1/'`"
while read i; do
	t=`echo $i | awk '{print $1}'`
	if [ $t -le `expr $lastT + 5` ]; then
		let "num += 1"
	else
		mod $lastT $num
		lastT=$t
		num=1
	fi
done <<< $sleepDat
mod $lastT $num

#Fill in zeros
sed -i 's/^\([0-9]*\) \([0-9]*\) \([0-9]*\) \([0-9]*\)$/\1 \2 \3 \4 0/' $file
