#!/bin/bash

export CLIC_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


usage() {
        echo "Usage:"
	echo "-u --user <name>         use <name> as the user for clic installation and use"
	echo "-n --namescheme <name>   use <name> as the base name for cluster instances"
	echo "-c --cloud               installing to a cloud computer"
	echo "-h --help                print this help message"
}

user=`whoami`
namescheme=`hostname`
cloud=false
ARGS=`getopt -n clic-install -o hgn:u: --long help,cloud,namescheme:,user: -- "$@"`
if [ $? != 0 ] ; then
        usage
        exit 1
fi
eval set -- "$ARGS"
while true; do
        case $1 in
                -h | --help)
                        usage
                        exit 0
                        ;;
                -c | --cloud)
                        cloud=true
                        shift
                        ;;
                -n | --namescheme)
                        namescheme="$2"
                        shift 2
                        ;;
                -u | --user)
                        user=$2
                        shift 2
                        ;;
                --)
                        shift
                        break
                        ;;
                *)
                        break
                        ;;
        esac
done

echo -n "Installing clic for user $user, using "
if [ "$cloud" == false ]; then
	echo -n "the google cloud instance named $namescheme as the basis for all compute nodes. The instance $namescheme must be currently running and "
else
	echo -n "this instance ($namescheme) as the basis for both the head and compute nodes. This instance must "
fi
echo "already have any desired computational software installed to it."
echo "Press ENTER to continue, or CTRL-c to exit."
read ans

if [ -n "`uname -a | grep -i Debian`" ]; then
   OS="debian"
elif [ -n "`uname -a | grep -i ubuntu`" ]; then
   OS="ubuntu"
elif [ -e "/etc/redhat-release" ]; then
   OS="centos"
else
   echo "Unidentified OS! Exiting."
   exit
fi
echo "Installing for $OS"

# Export our variables
export namescheme=$namescheme
export user=$user
export cloud=$cloud

$CLIC_ROOT/scripts/$OS/install_slurm
$CLIC_ROOT/scripts/common/install_clic
if [ "$cloud" == false ]; then
	$CLIC_ROOT/scripts/common/create_cloud_snapshot
fi
