#!/bin/bash

export CLIC_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage() {
        echo "Usage:"
	echo "Run this script to install CLIC to a cloud computer (pure cloud) or to a physical machine and a cloud computer (hybrid). If performing a pure cloud installation, execute this script on a computer other than the cloud computer. If performing a hybrid installation, execute this script on the physical head node."
	echo "--head <name>            use computer at <name> as the head node.
	                                   Default: localhost"
	echo "--compute <name>         use computer at <name> (not localhost) as the compute node.
	                                   Default: same value as <name> for head."
	echo "-s                       scripted, don't ask for confirmation"
	echo "--skip_slurm             don't install slurm"
	echo "-h --help                print this help message and exit"
}

export head="localhost"
export compute="localhost"
export namescheme=`hostname`
export script=false
export skip_slurm=false
export user=`whoami`

ARGS=`getopt -n clic-install -o hs --long help,skip_slurm,head:,compute:,zone: -- "$@"`
if [ $? != 0 ] ; then
        usage
        exit 1
fi
eval set -- "$ARGS"
while true; do
        case $1 in
                -h | --help)
                        usage
                        exit 0
                        ;;
		-s)
			export script=true;
			shift
			;;
		--head)
			export head="$2"
			shift 2
			;;
                --compute)
                        export compute="$2"
                        shift 2
                        ;;
		--zone)
			export zone="$2"
			shift 2
			;;
		--skip_slurm)
			export skip_slurm=true
			shift
			;;
                --)
                        shift
                        break
                        ;;
                *)
                        break
                        ;;
        esac
done

if [ "$compute" == "localhost" ]; then
	export compute="$head"
fi

export namescheme="$compute"

if [ -n "`curl -s 'http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip' -H 'X-Google-Metadata-Request: True'`" ]; then
	# A bit of a hack, but this api request only returns a non-empty string if run from within the cloud
	export cloud=true
else
	export cloud=false
fi

if [ -n "`uname -a | grep -i Debian`" ]; then
   OS="debian"
elif [ -n "`uname -a | grep -i ubuntu`" ]; then
   OS="ubuntu"
elif [ -e "/etc/redhat-release" ]; then
   OS="centos"
else
   OS="undef"
fi

if ! $script; then
	# Only do error checking if it isn't scripted
	if [ "$compute" == "localhost" ] || [ "$compute" == `hostname` ]; then
		echo "Must specify a compute instance that isn't localhost or `hostname`!"
		exit 1
	fi
	
	if [ "$OS" == "undef" ]; then
		echo "Warning: Unidentified OS! If this is a pure cloud installation, it's probably fine."
	fi

	echo -n "Installing clic using "
	if [ "$head" == "$compute" ]; then
		echo -n "the cloud instance $namescheme as the basis for both the head and compute nodes."
	else
		echo -n "the cloud instance $namescheme as the basis for all compute nodes, and this computer, $head, as the head node."
	fi
	echo " The instance $namescheme must be currently running and already have any desired computational software installed to it. Press ENTER to continue, or CTRL-c to exit."
	read ans
fi


if ! $cloud; then
	command -v gcloud >/dev/null 2>&1 || $CLIC_ROOT/scripts/$OS/setup_gcloud
	$CLIC_ROOT/scripts/common/setup_gcloud
fi

if ! $skip_slurm; then
	if [ "`hostname`" == "$head" ] || [ "`hostname`" == "$compute" ]; then
		$CLIC_ROOT/scripts/$OS/install_slurm
	fi
fi

if [ -z "$zone" ]; then
	export zone=`sudo su - -c "gcloud compute instances list | grep "$namescheme" | awk '{print \$2}'"`
fi

$CLIC_ROOT/scripts/common/install_clic

if [ "`hostname`" != "$compute" ]; then
	$CLIC_ROOT/scripts/common/create_cloud_image
fi

if ! $cloud; then
	echo "Please ensure that tcp ports 6817 (slurm) and 22 (ssh) are allowed through the firewall to this machine."
fi
