#!/bin/bash

CLIC_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export MUNGEUSER=981
sudo groupadd -g $MUNGEUSER munge
sudo useradd  -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge  -s /sbin/nologin munge
export SLURMUSER=982
sudo groupadd -g $SLURMUSER slurm
sudo useradd  -m -c "Slurm workload manager" -d /var/lib/slurm -u $SLURMUSER -g slurm  -s /bin/bash slurm

echo "Installing munge"
sudo yum -y install epel-release &> /dev/null
sudo yum -y install munge munge-libs munge-devel &> /dev/null

sudo dd if=/dev/urandom bs=1 count=1024 | sudo tee /etc/munge/munge.key > /dev/null
sudo chown munge:munge /etc/munge/munge.key
sudo chmod 400 /etc/munge/munge.key

sudo chown -R munge:munge /etc/munge/ /var/log/munge/
sudo chmod 0700 /etc/munge/ /var/log/munge/

sudo systemctl enable munge
sudo systemctl start munge

echo "Installing slurm build dependencies"
sudo yum -y install rpm-build gcc openssl openssl-devel pam-devel numactl numactl-devel hwloc hwloc-devel lua lua-devel readline-devel rrdtool-devel ncurses-devel gtk2-devel man2html libibmad libibumad perl-Switch perl-ExtUtils-MakeMaker &> /dev/null
sudo yum -y install mariadb-server mariadb-devel &> /dev/null

echo "Downloading and building slurm"
VER=`curl -s https://www.schedmd.com/downloads.php | grep -oP 'latest/slurm-.*?.tar.bz2' | head -n 1 | grep -o '\([0-9][0-9]*.\)*' | rev | cut -c 2- | rev`
cd /tmp
curl -O https://www.schedmd.com/downloads/latest/slurm-$VER.tar.bz2
rpmbuild -ta slurm-$VER.tar.bz2
cd ~/rpmbuild/RPMS/x86_64/
sudo yum -y install slurm-$VER*rpm slurm-devel-$VER*rpm slurm-munge-$VER*rpm slurm-perlapi-$VER*rpm slurm-plugins-$VER*rpm slurm-sjobexit-$VER*rpm slurm-sjstat-$VER*rpm slurm-torque-$VER*rpm slurm-seff-$VER*rpm

sudo mkdir /var/spool/slurmctld /var/log/slurm
sudo chown slurm: /var/spool/slurmctld /var/log/slurm
sudo chmod 755 /var/spool/slurmctld /var/log/slurm

sudo touch /var/log/slurm/slurmctld.log
sudo chown slurm: /var/log/slurm/slurmctld.log

sudo touch /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log
sudo chown slurm: /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log

# Set up exports. Only the head node needs this, but it isn't a problem to have this configured for all nodes.
sudo yum -y install nfs-utils &> /dev/null
echo -e "\n/etc/exports:"
cat $CLIC_ROOT/files/exports | sudo tee --append /etc/exports
sudo systemctl enable nfs
sudo systemctl start nfs

# Set up passwordless ssh between nodes
echo | ssh-keygen -N ""
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
echo -e "\nDisabling knownhost checking:"
echo "StrictHostKeyChecking no
UserKnownHostsFile=/dev/null
LogLevel error" | sudo tee --append /etc/ssh/ssh_config
# So that nodes can still access ~/.ssh when /home is mounted, there must be another mountpoint to bind it to.
mkdir /.ssh
chown `whoami`:`whoami` /.ssh
