#!/bin/bash

opts="-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error"
# One way or another, install git
ssh $opts $user@$namescheme "sudo yum -y install git || sudo apt -y install git"
# Install slurm
ssh $opts $user@$namescheme "rm -rf clic; git clone https://github.com/nathanrvance/clic; ./clic/install --cloud -s"
# Copy over munge key
#sudo scp $opts -i ~/.ssh/id_rsa /etc/munge/munge.key $user@$namescheme:.
#ssh $opts $user@$namescheme "sudo cp -f /home/$user/munge.key /etc/munge/munge.key && sudo chown munge:munge /etc/munge/munge.key && sudo chmod 400 /etc/munge/munge.key"
# Copy over slurm.conf
scp $opts /etc/slurm/slurm.conf $user@$namescheme:.
ssh $opts $user@$namescheme "sudo mv -f /home/$user/slurm.conf /etc/slurm/slurm.conf && sudo chown root:root /etc/slurm/slurm.conf && sudo chmod 644 /etc/slurm/slurm.conf"
# Copy over slurm keys
sudo scp $opts -i ~/.ssh/id_rsa /etc/slurm/slurm.key $user@$namescheme:.
ssh $opts $user@$namescheme "sudo mv -f /home/$user/slurm.key /etc/slurm/slurm.key && sudo chown slurm:slurm /etc/slurm/slurm.key && sudo chmod 400 /etc/slurm/slurm.conf"
scp $opts /etc/slurm/slurm.cert $user@$namescheme:.
ssh $opts $user@$namescheme "sudo mv -f /home/$user/slurm.cert /etc/slurm/slurm.cert && sudo chown root:root /etc/slurm/slurm.cert && sudo chmod 644 /etc/slurm/slurm.cert"
# Copy back ssh key
ssh $opts $user@$namescheme "cat ~/.ssh/id_rsa.pub" >> ~/.ssh/authorized_keys

# Test sshfs
clic-remote-mount `whoami` $user $namescheme
ssh $opts $user@$namescheme "touch ~/foo"
if [ ! -e ~/foo ]; then
	echo "Failed to create file remotely!"
	exit 1
fi
rm ~/foo

# Stop and snapshot the instance
echo "Stopping $namescheme"
gcloud compute instances stop $namescheme
gcloud compute disks snapshot $namescheme --snapshot-names=$namescheme

echo "You are free to delete the instance named $namescheme if you desire."
