#!/bin/bash

# One way or another, install git
ssh $user@$namescheme sudo yum -y install git || sudo apt -y install git
# Install slurm
ssh $user@$namescheme git clone https://github.com/nathanrvance/clic && ./clic/install --cloud -s
# Copy over munge key
scp /etc/munge/munge.key $user@$namescheme:.
ssh $user@$namescheme sudo rm /etc/munge/munge.key && sudo cp /home/$user/munge.key /etc/munge/ && sudo chown munge:munge /etc/munge/munge.key && sudo chmod 400 /etc/munge/munge.key
# Copy over slurm.conf
scp /etc/slurm/slurm.conf $user@$namescheme:.
ssh $user@$namescheme sudo rm /etc/slurm/slurm.conf && sudo cp /home/$user/slurm.conf /etc/slurm/ && sudo chown root:root /etc/slurm/slurm.conf && sudo chmod 644 /etc/slurm/slurm.conf

# Stop and snapshot the instance
echo "Stopping $namescheme"
gcloud compute instances stop $namescheme
gcloud compute disks snapshot $namescheme --snapshot-names=$namescheme

echo "You are free to delete the instance named $namescheme if you desire."
