#!/bin/bash

echo "Using $namescheme as the base name for the cluster"

#Install clic modules
sudo su - -c "pip3 install $CLIC_ROOT/src --upgrade"

#Run some of them
source ~/.bashrc
if ! $cloud; then
	sudo clic-synchosts
fi
sudo clic-copyid --generate --append -u `whoami` $user `whoami`

#Create a config file
sudo mkdir /etc/clic/
echo -e "\n/etc/clic/clic.conf:"
cat $CLIC_ROOT/files/clic.conf | sed "s/NAMESCHEME/$namescheme/g" | sed "s/CLOUD/$cloud/g" | sed "s/USER/$user/g" | sudo tee /etc/clic/clic.conf

#And a readme
echo -e "\n/etc/clic/README:"
echo "
When clic-initnode is run, either manually or by clic, all executable files in this
directory are copied to the node being initialized and run in shell expansion order." | sudo tee /etc/clic/README

#Create a service to start the clic daemon
echo -e "\n/etc/systemd/system/clic.service:"
path="`which clic`"
cat $CLIC_ROOT/files/clic.service | sed "s&PATH&$path&g" | sudo tee /etc/systemd/system/clic.service

sudo systemctl enable clic.service
sudo systemctl restart clic.service
