#!/bin/bash

echo "Using $namescheme as the base name for the cluster"

#Create a daemon that runs clic
echo -e "\n/usr/bin/clic:"
cat $CLIC_ROOT/files/clic | sed "s/CLOUD/$cloud/g" | sed "s/NAMESCHEME/$namescheme/g" | sed "s/REMOTEUSER/`whoami`/g" | sed "s/USER/$user/g" | sed "s&KEY&/home/`whoami`/.ssh/id_rsa&g" | sudo tee /usr/bin/clic
sudo chmod +x /usr/bin/clic

#Move helper scripts into place
echo -e "\n/usr/bin/clic-sync-hosts:"
cat $CLIC_ROOT/files/clic-sync-hosts | sudo tee /usr/bin/clic-sync-hosts
sudo chmod +x /usr/bin/clic-sync-hosts
sudo clic-sync-hosts

echo -e "\n/usr/bin/clic-nodesup:"
cat $CLIC_ROOT/files/clic-nodesup | sed "s/USER/$user/g" | sed "s&KEY&/home/`whoami`/.ssh/id_rsa&g" | sudo tee /usr/bin/clic-nodesup
sudo chmod +x /usr/bin/clic-nodesup

echo -e "\n/usr/bin/clic-remote-mount:"
cat $CLIC_ROOT/files/clic-remote-mount | sed "s/CLOUD/$cloud/g" | sudo tee /usr/bin/clic-remote-mount
sudo chmod +x /usr/bin/clic-remote-mount

echo -e "\n/usr/bin/clic-copy-id:"
cat $CLIC_ROOT/files/clic-copy-id | sudo tee /usr/bin/clic-copy-id
sudo chmod +x /usr/bin/clic-copy-id
sudo clic-copy-id --append -u `whoami` $user `whoami`

#Create a service to start the clic daemon
echo -e "\n/etc/systemd/system/clic.service:"
cat $CLIC_ROOT/files/clic.service | sudo tee /etc/systemd/system/clic.service
sudo systemctl enable clic.service
sudo systemctl restart clic.service
