#!/bin/bash

# This script does not install gcloud or perform the first time setup, but rather configures google cloud for use with clic

echo "Allowing tcp port 6818 for cloud instances"
gcloud beta compute firewall-rules create "slurmd" --allow tcp:6818 --direction "INGRESS" --priority "1000" --network "default" --source-ranges "0.0.0.0/0"

echo "Allowing passwordless ssh from user account `whoami` on this machine to $user on cloud instances"
gcloud compute project-info add-metadata --metadata=sshKeys="$(echo "$(gcloud compute project-info describe | grep -Pzo '(?s)key: sshKeys.*?kind:' | tail -n +2 | head -n -1 | perl -pe 's/\|-?\s*//' | sed 's/\s*value:\s*//' | sed 's/^\s*//' | sed 'N;s/\n\(\S*@\S*\)/ \1/')
$user:`cat ~/.ssh/id_rsa.pub`" | sed '/^\s*$/d')"
