#!/bin/bash

# This script does not install gcloud or perform the first time setup, but rather configures google cloud for use with clic

if ! $cloud; then
	# Make sure gcloud is set up for the root user
	if sudo [ ! -e /root/.config/gcloud/application_default_credentials.json ]; then
		echo "Obtaining oauth2 credentials"
		sudo su - -c "gcloud auth application-default login"
		mkdir -p /home/`whoami`/.config/gcloud/
		sudo cp /root/.config/gcloud/application_default_credentials.json /home/`whoami`/.config/gcloud/application_default_credentials.json
		sudo chown `whoami`:`whoami` /home/`whoami`/.config/gcloud/application_default_credentials.json

		echo "Logging in as user"
		sudo su - -c "gcloud init"
	fi
fi
