#!/bin/bash

export API_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $API_ROOT/api.conf

zone=`gcloud compute instances list | grep "$(hostname)" | awk '{print $2}'`

gcloud config set compute/zone $zone

cmd=$1
rest="${@:2}"
if [ -z "$rest" ]; then
	rest=$NAME_BASE
fi
$API_ROOT/scripts/$cmd $rest
