#!/bin/bash

export API_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $API_ROOT/api.conf
#export SITC_ROOT="$API_ROOT/../../"
#source $SITC_ROOT/install.conf

#if [ `whoami` != "$WEBMO_USER" ]; then
#	if [ ! -e /home/$WEBMO_USER/sitc/scripts/api/api ]; then
#                sudo su - $WEBMO_USER -c "cp -a $SITC_ROOT /home/$WEBMO_USER/sitc"
#        fi
#	echo "Switching to user $WEBMO_USER..."
#        sudo su - $WEBMO_USER -c "/home/$WEBMO_USER/sitc/scripts/api/api $*"
#	exit
#fi

#Make sure gcloud is up to date
#gcloud=`which gcloud`
#echo "Y" | sudo $gcloud components update

zone=`gcloud compute instances list | grep "$(hostname)" | awk '{print $2}'`

gcloud config set compute/zone $zone

cmd=$1
rest="${@:2}"
if [ -z "$rest" ]; then
	rest=$NAME_BASE
fi
$API_ROOT/scripts/$cmd $rest
