#!/bin/bash

# Install build dependencies
echo "Installing build dependencies"
sudo apt update >> $CLIC_ROOT/clic.log 2>&1
sudo apt -y install libalgorithm-c3-perl libarchive-extract-perl libcgi-fast-perl libcgi-pm-perl libclass-c3-perl libclass-c3-xs-perl libcpan-meta-perl libdata-optlist-perl libdata-section-perl libfcgi-perl libhwloc-plugins libhwloc5 liblog-message-perl liblog-message-simple-perl libltdl7 liblua5.1-0 libmodule-build-perl libmodule-pluggable-perl libmodule-signature-perl libmro-compat-perl libmysqlclient20 libnuma1 libpackage-constants-perl libparams-util-perl libpciaccess0 libpod-latex-perl libpod-readme-perl libregexp-common-perl libsoftware-license-perl libsub-exporter-perl libsub-install-perl libterm-ui-perl libtext-soundex-perl libtext-template-perl libxml2 mysql-common ocl-icd-libopencl1 openssl-blacklist perl perl-modules rename sgml-base xml-core gcc make bzip2 libssl-dev lua5.2 liblua5.2-dev >> $CLIC_ROOT/clic.log 2>&1
#sudo apt -y install munge libmunge2 libmunge-dev &> /dev/null
sudo apt -y install nfs-kernel-server sshfs python3-pip >> $CLIC_ROOT/clic.log 2>&1

# Munge yells because /var/log is group writable, but this patch fixes that. Somehow.
#sudo sed -i 's&ExecStart=/usr/sbin/munged&ExecStart=/usr/sbin/munged --syslog&' /lib/systemd/system/munge.service
#sudo systemctl daemon-reload
#sudo systemctl enable munge
#sudo systemctl start munge

$CLIC_ROOT/scripts/common/install_slurm

# Enable/start nfs
sudo systemctl enable nfs-kernel-server 
sudo systemctl restart nfs-kernel-server 
sudo systemctl enable nfs-idmapd
sudo systemctl start nfs-idmapd
