#!/bin/bash

# Install a bunch of stuff
echo "Installing build dependencies"
sudo yum -y install epel-release &> /dev/null
#sudo yum -y install munge munge-libs munge-devel &> /dev/null
sudo yum -y install rpm-build gcc openssl openssl-devel pam-devel numactl numactl-devel hwloc hwloc-devel lua lua-devel readline-devel rrdtool-devel ncurses-devel gtk2-devel man2html libibmad libibumad perl-Switch perl-ExtUtils-MakeMaker &> /dev/null
sudo yum -y install mariadb-server mariadb-devel &> /dev/null
sudo yum -y install nfs-utils bind-utils fuse-sshfs python34 &> /dev/null

# Actually do the installation
$CLIC_ROOT/scripts/common/install_slurm

# Enable and start nfs (this is platform specific)
sudo systemctl enable nfs
sudo systemctl start nfs
