#!/bin/bash

export MUNGEUSER=981
sudo groupadd -g $MUNGEUSER munge
sudo useradd  -m -c "MUNGE Uid 'N' Gid Emporium" -d /var/lib/munge -u $MUNGEUSER -g munge  -s /sbin/nologin munge
export SLURMUSER=982
sudo groupadd -g $SLURMUSER slurm
sudo useradd  -m -c "Slurm workload manager" -d /var/lib/slurm -u $SLURMUSER -g slurm  -s /bin/bash slurm

echo "Installing munge"
sudo apt -y install munge libmunge2 libmunge-dev &> /dev/null

sudo dd if=/dev/urandom bs=1 count=1024 | sudo tee /etc/munge/munge.key > /dev/null
sudo chown munge:munge /etc/munge/munge.key
sudo chmod 400 /etc/munge/munge.key

sudo chown -R munge:munge /etc/munge/ /var/log/munge/
sudo chmod 0700 /etc/munge/ /var/log/munge/

sudo systemctl enable munge
sudo systemctl start munge

echo "Installing slurm build dependencies"
sudo apt -y install libalgorithm-c3-perl libarchive-extract-perl libcgi-fast-perl libcgi-pm-perl libclass-c3-perl libclass-c3-xs-perl libcpan-meta-perl libdata-optlist-perl libdata-section-perl libfcgi-perl libhwloc-plugins libhwloc5 liblog-message-perl liblog-message-simple-perl libltdl7 liblua5.1-0 libmodule-build-perl libmodule-pluggable-perl libmodule-signature-perl libmro-compat-perl libmysqlclient18 libnuma1 libpackage-constants-perl libparams-util-perl libpciaccess0 libpod-latex-perl libpod-readme-perl libregexp-common-perl libsoftware-license-perl libsub-exporter-perl libsub-install-perl libterm-ui-perl libtext-soundex-perl libtext-template-perl libxml2 mysql-common ocl-icd-libopencl1 openssl-blacklist perl perl-modules rename sgml-base xml-core gcc make bzip2

VER=`curl -s https://www.schedmd.com/downloads.php | grep -oP 'latest/slurm-.*?.tar.bz2' | head -n 1 | grep -o '\([0-9][0-9]*.\)*' | rev | cut -c 2- | rev`
cd /tmp
curl -O https://www.schedmd.com/downloads/latest/slurm-$VER.tar.bz2
tar xjf slurm-$VER.tar.bz2
cd slurm-$VER
./configure --prefix=/usr --sysconfdir=/etc/slurm
make
sudo make install

echo "[Unit]
Description=Slurm controller daemon
After=network.target munge.service
ConditionPathExists=/etc/slurm/slurm.conf

[Service]
Type=forking
EnvironmentFile=-/etc/sysconfig/slurmctld
ExecStart=/usr/sbin/slurmctld \$SLURMCTLD_OPTIONS
ExecReload=/bin/kill -HUP \$MAINPID
PIDFile=/var/run/slurmctld.pid

[Install]
WantedBy=multi-user.target" | sudo tee /etc/systemd/system/slurmctld.service

echo "[Unit]
Description=Slurm node daemon
After=network.target munge.service
ConditionPathExists=/etc/slurm/slurm.conf

[Service]
Type=forking
EnvironmentFile=-/etc/sysconfig/slurmd
ExecStart=/usr/sbin/slurmd \$SLURMD_OPTIONS
ExecReload=/bin/kill -HUP \$MAINPID
PIDFile=/var/run/slurmd.pid
KillMode=process
LimitNOFILE=51200
LimitMEMLOCK=infinity
LimitSTACK=infinity

[Install]
WantedBy=multi-user.target" | sudo tee /etc/systemd/system/slurmd.service

sudo mkdir /var/spool/slurmctld /var/log/slurm
sudo chown slurm: /var/spool/slurmctld /var/log/slurm
sudo chmod 755 /var/spool/slurmctld /var/log/slurm

sudo touch /var/log/slurm/slurmctld.log
sudo chown slurm: /var/log/slurm/slurmctld.log

sudo touch /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log
sudo chown slurm: /var/log/slurm/slurm_jobacct.log /var/log/slurm/slurm_jobcomp.log

sudo mkdir /etc/slurm
sudo chown slurm: /etc/slurm

# Set up exports. Only the head node needs this, but it isn't a problem to have this configured for all nodes.
echo -e "\n/etc/exports:"
sudo apt -y install nfs-kernel-server
cat $CLIC_ROOT/files/exports | sudo tee --append /etc/exports
sudo systemctl enable nfs-kernel-server 
sudo systemctl start nfs-kernel-server 

# Set up passwordless ssh between nodes
echo | ssh-keygen -N ""
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
echo -e "\nDisabling knownhost checking:"
echo "StrictHostKeyChecking no
UserKnownHostsFile=/dev/null
LogLevel error" | sudo tee --append /etc/ssh/ssh_config
# So that nodes can still access ~/.ssh when /home is mounted, there must be another mountpoint to bind it to.
sudo mkdir /.ssh
sudo chown `whoami`:`whoami` /.ssh
