#!/usr/bin/python3
import argparse
import ipgetter
import os
import re
from pathlib import Path
from pwd import getpwnam

parser = argparse.ArgumentParser(description='Remote mount home directory (NOTE: preserves remote /home/*/.ssh)')
parser.add_argument('userhost', metavar='USER@HOST', nargs=1, help='passwordless ssh exists both ways between USER@HOST and USER@localhost')
args = parser.parse_args()

#Error checking
if not re.search('^\w+@\w+$', args.userhost[0]):
    parser.error('incorrect formatting: ' + args.userhost[0])

ip = ipgetter.myip()
[user, host] = args.userhost[0].split('@')
hostname = os.popen('hostname -s').read().strip()
sshOpts = '-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error'

#os.system('sudo clic-copy-id --append --generate')
os.system('sudo ssh -i /home/{0}/.ssh/id_rsa {2} {0}@{1} "sudo clic-sync-hosts {3} {4}"'.format(user, host, sshOpts, hostname, ip))

#Set up ssh tunnel
os.system('sudo ssh -i /home/{0}/.ssh/id_rsa {2} {0}@{1} "ssh -fN -L 3049:localhost:2049 {0}@{3}"'.format(user, host, sshOpts, hostname))
#Set up nfs
os.system('sudo ssh -i /home/{0}/.ssh/id_rsa {2} {0}@{1} "sudo mkdir /bind-root; sudo mount --bind / /bind-root; sudo mount -t nfs4 -o port=3049 localhost:/home /home && ( for user in \`ls /bind-root/home\`; do sudo mount --bind /bind-root/home/\$user/.ssh /home/\$user/.ssh; done ) &"'.format(user, host, sshOpts))
