#!/bin/bash

# NAMESCHEME is the name of the head node, and all NAMESCHEMEXX are compute nodes.

TWIDDLE_TIME=20

mainLoop() {
	topJob=0
	topJobEnq=`uptime`
	while [ "true" ]; do
		echo "Doing stuff"
		# Queued and running jobs are one line each containing the job number
		rJobs=`qstat -r | tail -n+6 | awk '{print $1}'`
		qJobs=`qstat -i | tail -n+6 | awk '{print $1}'`
		
		if [ "$topJob" != "`echo $qJobs | head -n 1`" ]; then
			# A job was run
			topJob=`echo $qJobs | head -n 1`
			topJobEnq=`uptime`
		fi
		
		if [ -n "$topJob" ] && [ $topJobEnq -lt $((${uptime}-TWIDDLE_TIME)) ]; then
			# Time to boot up another compute node
			echo "I want to make another node!"
		fi

		if [ -z "$topJob" ] && [ $topJobEnq -lt $((${uptime}-TWIDDLE_TIME)) ]; then
			# Time to shut down a compute node
			echo "I want to delete a node!"
		fi

		sleep 10
	done
}

uptime() {
	cat /proc/uptime | awk '{print $1}' #In seconds
}

if [ "`hostname`" == "NAMESCHEME" ]; then
        # do head node stuff
        echo "Starting slurmctld.service"
        systemctl start slurmctld.service
	mainLoop &
else
        # do compute node stuff
        #echo "NAMESCHEME:/etc/slurm            /etc/slurm              nfs     ro,hard,intr    0 0" | sudo tee --append /etc/fstab > /dev/null
        #echo "NAMESCHEME:/etc/munge            /etc/munge              nfs     ro,hard,intr    0 0" | sudo tee --append /etc/fstab > /dev/null
        #echo "NAMESCHEME:/home                 /home                   nfs     rw,hard,intr    0 0" | sudo tee --append /etc/fstab > /dev/null
        sudo mount NAMESCHEME:/etc/slurm /etc/slurm --ro
        sudo mount NAMESCHEME:/etc/munge /etc/munge --ro
	sudo mount NAMESCHEME:/home /home --rw
        echo "Starting slurmd.service"
        systemctl start slurmd.service
fi
