#!/usr/bin/python3
import argparse
import os

parser = argparse.ArgumentParser(description='Determine which nodes are up')
parser.add_argument('-r', '--running', action='store_true', help='report only nodes that can accept ssh connections (default: includes booting)')
args = parser.parse_args()


