#!/bin/bash

name=$1
number=$2

$API_ROOT/scripts/lowlevel/start_snapshot $name$number $name

# Set up the new server
cd /home/$WEBMO_USER/public_html/cgi-bin/webmo
perl -e "require qw(servercontrol.cgi);
add_server(\"$name$number\", \"$name$number\", \"$NUMCPUS\", \"$WEBMO_USER\", \"/home/$WEBMO_USER\", \"/tmp\", \"ssh\");"

# Aquire the engines and enginedir for the server
source $API_ROOT/$name

serverDir=`grep -o "$name$number,[0-9]\+" /home/$WEBMO_USER/public_html/cgi-bin/webmo/interfaces/globals.int | cut -d ',' -f2`
serverDir="/home/$WEBMO_USER/public_html/cgi-bin/webmo/servers/server_$serverDir/"

